OPENAI_API_KEY: "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"
PINECONE_API_KEY: "96681236-0762-4ae8-82a4-17aeda878cdf"
GOOGLE_API_KEY: "AIzaSyBeJj4s_JDVoUwKZrYgvK0bTms6CtWCCUo"